# Generated by Django 4.2.17 on 2025-01-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('users only', 'Users Only'), ('public', 'Public')], default='users only', max_length=15),
        ),
    ]
