# Generated by Django 4.2.17 on 2025-01-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('users only', 'Users Only'), ('public', 'Public')], max_length=15),
        ),
    ]
