# Generated by Django 4.2.17 on 2025-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Users Only', 'Users Only'), ('Public', 'Public')], max_length=15),
        ),
    ]
