# Generated by Django 4.2.17 on 2026-01-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
